### ISSUE TITLE
update tinymce to v4.1.7

### ISSUE THREAD

**Issue by softwaymedical** [artursmirnov/tinymce_builded#3]
Could you please update to v4.1.7 in order that we use it.

Hopefully that [tinymce-dist](https://github.com/tinymce/tinymce-dist) will bundle a new version with all languages regarding issue https://github.com/tinymce/tinymce-dist/issues/8.

**Comment by artursmirnov** [comment]
@softwaymedical sorry for some delay, I updated the package to the latest stable version of tinymce which is 4.1.9.
