### ISSUE TITLE
Can we get an update to tinymce 4.2.5?

### ISSUE THREAD

**Issue by vangheem** [artursmirnov/tinymce_builded#4]

**Comment by artursmirnov** [comment]
I updated tinymce to latest version. Sorry for the delay, I didn't think someone still using it. If so, I'll keep updating the repo as soon as new versions gets released.

**Comment by vangheem** [comment]
Thanks!

**Comment by vangheem** [comment]
hhmm, bower isn't pulling it in. Can you tag it?

**Comment by artursmirnov** [comment]
Oh, sure. Done. Forgot `--tags` when pushed
