### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by thet** [artursmirnov/tinymce_builded#6]
There is a new ``tinymce`` release: 4.3.4.
Can we have an updated version of ``tinymce_bundled``?
Is there a way to volunteer for this work? We're using this repo for Plone and want to get TinyMCE bugfixes in more frequently.

@artursmirnov could you imagine to give some of us contribution access to this repo and describe the build process?

**Comment by artursmirnov** [comment]
@thet sorry for the delay, I'll update the package shortly. 

In the updated package I will describe update process (It's pretty simple though) in README.md file and after that I'll add you as a contributor to the repository. Would that work for you?

**Comment by thet** [comment]
@artursmirnov no prob for delays! And it sounds great - So I don't have to bother you when I feel like I need a new TinyMCE release for Plone. Thanks a lot in advance!

**Comment by artursmirnov** [comment]
I [updated](https://github.com/artursmirnov/tinymce_builded/pull/7) the package to the latest 4.3.4 version of TinyMCE and added the update process description to [README.md](README.md) file. Also @thet is now a contributor in this repo. If you have any questions please feel free to ask me.

**Comment by thet** [comment]
Thanks! The update process looks simple, I agree. I'll try it as soon as I recognize a new TinyMCE version :)
